/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#eee0d7",
        "surface-container": "#ffe9e5",
        "surface-container-low": "#fff0ee",
        "surface-dim": "#eed4d0",
        "inverse-primary": "#ffb4a6",
        "tertiary": "#006480",
        "error": "#ba1a1a",
        "on-surface": "#261816",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#001f2a",
        "primary-fixed-dim": "#ffb4a6",
        "surface": "#fff8f6",
        "on-error": "#ffffff",
        "surface-tint": "#b12c1a",
        "on-tertiary-fixed-variant": "#004d64",
        "tertiary-fixed": "#bde9ff",
        "on-primary-fixed": "#400200",
        "tertiary-container": "#007ea1",
        "outline-variant": "#e2bfb8",
        "inverse-on-surface": "#ffedea",
        "primary-container": "#d0422d",
        "inverse-surface": "#3d2d2a",
        "secondary": "#665d56",
        "background": "#fff8f6",
        "on-tertiary": "#ffffff",
        "primary": "#ae2917",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffdad4",
        "on-secondary-container": "#6c635c",
        "error-container": "#ffdad6",
        "on-surface-variant": "#5a413c",
        "tertiary-fixed-dim": "#72d2fa",
        "surface-container-highest": "#f7ddd8",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#fbfdff",
        "outline": "#8e706b",
        "surface-container-high": "#fde2de",
        "surface-bright": "#fff8f6",
        "secondary-fixed-dim": "#d1c4bc",
        "secondary-container": "#eee0d7",
        "on-primary-fixed-variant": "#8f1103",
        "on-secondary-fixed": "#211a15",
        "on-secondary-fixed-variant": "#4e453f",
        "surface-variant": "#f7ddd8",
        "on-primary-container": "#fffbff",
        "on-background": "#261816",
        "on-error-container": "#93000a",
        "vellum": "#FDFCF8",
        "fresh-paper": "#FCFAF5",
        "warm-onyx": "#1A1A1A",
        "onyx": "#1A1A1A",
        "muted-taupe": "#726861",
        "vermilion": "#D64933",
        "library-green": "#285943"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "sm": "0.125rem"
      },
      spacing: {
        "margin-page": "48px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "padding-card": "24px",
        "unit": "4px",
        "gutter": "24px",
        "stack-md": "16px"
      },
      fontFamily: {
        "headline-lg": ["Playfair Display", "serif"],
        "body-md": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-lg": ["Playfair Display", "serif"],
        "serif": ["Playfair Display", "serif"],
        "sans": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "label-lg": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
